package edu.fullerton.ecs.cpsc476.dao;

import org.skife.jdbi.v2.sqlobject.SqlUpdate;

public interface DatabaseDAO 
{
	@SqlUpdate("create schema skimmdit")
	int createSchema();
	
	@SqlUpdate("create table skimmdit.user(id int GENERATED BY DEFAULT AS IDENTITY, userName varchar(255) NOT NULL, password varchar(255) NOT NULL)")
	int createUserTable();
	
	@SqlUpdate("create table skimmdit.article(id int GENERATED BY DEFAULT AS IDENTITY, articleName varchar(255) NOT NULL, articleUrl varchar(255) NOT NULL, time TIMESTAMP NOT NULL,vote int not null, userId int Not Null)")
	int createArticleTable();
	
	@SqlUpdate("create table skimmdit.vote (id int GENERATED BY DEFAULT AS IDENTITY, articleid int, userid int, type int)")
	int createVoteTable();
}
